# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027be92cb5be75c7b74c7e18422144b96b566cab069b3e1536f2201b705e3f3d9567455b5d9bf8584079cbef6a28d297d9092ce0628f34eaaac08b5d932a3f8d

test:
  secret_key_base: 2db73cfa1d768856238be54939b25c66586bb91ae570daa99ee77963d494bba8292a64c2757aadd8c35e1239a3c47e4578109ced56197cf77fb37175a44c33b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
